from os import getenv
from Nexa.data import Ivan

API_ID = int(getenv("API_ID", "25981592"))
API_HASH = getenv("API_HASH", "709f3c9d34d83873d3c7e76cdd75b866")
SESSION1 = getenv("SESSION")
OWNER_ID = int(getenv("OWNER_ID", "8553815122"))
HEROKU_APP_NAME = getenv("HEROKU_APP_NAME")
HEROKU_API_KEY = getenv("HEROKU_API_KEY")
OPENAIKEY = getenv("OPENAIKEY")
SESSION2 = getenv("SESSION2", "AQI5nD4AdJzMUFwRI2m7cAQe7bRdibZ5EX7G67u5PMzDQhXoHSr1fr7y-R9Hqw5q2qM5hO53rrRmo9OkxyqZKt8DYBN9WPMOvLMLbl2ZrB2itODUwIuk2S07D3OHcq1BJQkXIaaA5PPh4ZYmMHwNRvzYg-tjNvLgs2PSB1ClNL-K-QdsIKtHePp7Cn-Iw2nyIsnudGKqvOTPI_kumRL56sfi9kw3JpIiq4YDI4Ue9d5mohKf-KdFF2mtvuGn9DjGzIvc3CuJsSSQD1PF9XWmElRT89ML928cuW8dTgXSgDS9KzkUrMsy4WanpjBLw5BZAAdI8RI6TpKujGNuxizojea7RGw3VwAAAAH8fZf_AA")
SESSION3 = getenv("SESSION3")
SESSION4 = getenv("SESSION4")
SESSION5 = getenv("SESSION5")
SESSION6 = getenv("SESSION6")
SESSION7 = getenv("SESSION7")
SESSION8 = getenv("SESSION8")
SESSION9 = getenv("SESSION9")
SESSION10 = getenv("SESSION10")
SUDOS = getenv("SUDO_USERS", None)
SUDO_USERS = []
if SUDOS:
    sudos = str(SUDOS).split(" ")
    for sudo_id in sudos:
        SUDO_USERS.append(int(sudo_id))
SUDO_USERS.append(OWNER_ID)
for x in STORMS:
    SUDO_USERS.append(x)
SESSIONS = [SESSION1, SESSION2, SESSION3, SESSION4, SESSION5, SESSION6, SESSION7, SESSION8, SESSION9, SESSION10]
